#!/bin/bash
flutter build apk
mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-game_app_flutter.apk
rclone copy build/app/outputs/flutter-apk/app-game_app_flutter.apk drive:/apks/ -P
